"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const input = require("prompt-sync")({ sigint: true });
const pcBuilder_1 = __importDefault(require("./pcBuilder"));
const pc = new pcBuilder_1.default();
pc.start();
const main = input("\nPick Mainboard id : ");
console.log("\n\n\n\n");
pc.getMain(main - 1);
const chip = input("\nPick Chip id : ");
console.log("\n\n\n\n");
pc.getChip(chip - 1);
const gpu = input("\nPick GPU id : ");
console.log("\n\n\n\n");
pc.getGPU(gpu - 1);
const ram = input("\nPick Ram id : ");
console.log("\n\n\n\n");
pc.getRam(ram - 1);
const psu = input("\nPick PSU id : ");
console.log("\n\n\n\n");
pc.getPSU(psu - 1);
const ssd = input("\nPick SSD id : ");
console.log("\n\n\n\n");
pc.getSSD(ssd - 1);
console.log("\n\n\nYour builded PC :");
console.log(pc.buildedParts);
